name: tests
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                architecture:
                - x64
                - ppc64le
                node-version:
                - 14.x
                - 12.x
                - 10.x
        name: ${{ matrix.node-version }} on ${{ matrix.architecture }}
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
              architecture: ${{ matrix.architecture }}
              node-version: ${{ matrix.node-version }}
        - run: npm install-test
